version: "3"
services:
  spark:
    image: peralozac/sparkmagic_spark:latest
    hostname: spark
    ports:
      - "8998:8998"
    volumes:
      - ./data:/home/jovyan/data
  jupyter:
    image: ramkris22/sparkmagic:v1.4
    links:
      - spark
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
    user: root
    environment:
      - GRANT_SUDO=yes
