version: "3"
services:
  spark:
    image: peralozac/sparkmagic_spark:latest
    hostname: spark
    ports:
      - "8998:8998"
    volumes:
      - ../../data:/data
  jupyter:
    image: ramkris22/sparkmagic:v1.4
    links:
      - spark
    ports:
      - "8888:8888"
    volumes:
      - ../../data:/data
      - ../../notebooks:/notebooks
    user: root
    command: "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --notebook-dir=/notebooks --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.iopub_data_rate_limit='1.0e10' --no-browser"
    environment:
      - GRANT_SUDO=yes
      - PROJ_LIB=/opt/conda/share/proj
  datascience:
    image: flaviostutz/datascience-tools:2.9.2
    ports:
      - "9999:8888"
    volumes:
      - ../../data:/data
      - ../../notebooks:/notebooks
    user: root
    command: "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --notebook-dir=/notebooks --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.iopub_data_rate_limit='1.0e10' --no-browser"
    environment:
      - GRANT_SUDO=yes
